spring:
  application:
    name: PetStore
  data:
    jdbc:
      dialect: postgresql
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:5432/petstore"
    username: "postgres"
    password: "test1234"
api:
  key: "petstore-api-key"
  cors:
    allowed-origins: http://127.0.0.1:4200, http://::1:4200, http://localhost:4200
logging:
  level:
    root: debug