services:
  database:
    build:
      context: sql
      dockerfile: ./Dockerfile
    container_name: database
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=petstore
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d petstore'"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: ..
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/petstore

  frontend:
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend